Type        : Blog
Title       : Jim Raynor
Logo        : photos/gerona.default.jpg
About       : Travel to Earth
Navigation  : Contact me, mailto:jim.raynor@mail.com
Per Page    : 1
MountAsRoot : true
Language    : ru
